apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: angelpay-prod

resources:
  - ../../base

images:
  - name: ghcr.io/zhima-001/angelpay
    newTag: 14a489c

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml
