apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: angelpay
  labels:
    app: angelpay
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: angelpay.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: angelpay
                port:
                  number: 80
